{% set name = "bravado" %}
{% set version = "10.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2b0ae6d190ab699646261eb569a24902683a25d3834473d1f88c78ab88ca854

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - bravado-core >=5.16.1
    - monotonic
    - msgpack-python
    - python
    - python-dateutil
    - pyyaml
    - requests >=2.17
    - simplejson
    - six
    - typing-extensions

test:
  imports:
    - bravado
    - bravado.testing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Yelp/bravado
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for accessing Swagger-enabled API's

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
